export const getTranslation = (key, lang = "en") => {
  const translations = {
    en: {
      good_morning: "Good Morning",
      good_afternoon: "Good Afternoon",
      good_evening: "Good Evening",
      hospitals: "Hospitals",
      dashboard: "Dashboard",
      diseases: "Diseases",
      medicines: "Medicines",
      settings: "Settings",
      logout: "Logout",
      find_hospitals: "Find Hospitals",
      ai_chat: "AI Chat Assistant",
      disease_registry: "Disease Registry",
      medicine_directory: "Medicine Directory",
      portal_actions: "Quick Portal Actions",
      my_appointments: "My Appointments",
      incoming_bookings: "Incoming Bookings",
      live_portal: "Live Portal",
      authorized_account: "Authorized Account",
      total_bookings: "Total Bookings",
      approved_visits: "Approved Visits",
      pending_reviews: "Pending Reviews",
      active_doctors: "Active Doctors",
      pending_approvals: "Pending Approvals",
      manage_doctors: "Manage Doctors",
      review_appointments: "Review Appointments",
      hospital_profile: "Hospital Profile",
      account_settings: "Account Settings",
      no_appointments: "No appointments scheduled",
    },
    hi: {
      good_morning: "शुभ प्रभात",
      good_afternoon: "शुभ दोपहर",
      good_evening: "शुभ संध्या",
      hospitals: "अस्पताल",
      dashboard: "डैशबोर्ड",
      diseases: "बीमारियां",
      medicines: "दवाइयाँ",
      settings: "सेटिंग्स",
      logout: "लॉगआउट",
      find_hospitals: "अस्पताल खोजें",
      ai_chat: "एआई चैट सहायक",
      disease_registry: "बीमारी रजिस्ट्री",
      medicine_directory: "दवा निर्देशिका",
      portal_actions: "त्वरित पोर्टल कार्य",
      my_appointments: "मेरे अपॉइंटमेंट",
      incoming_bookings: "आने वाली बुकिंग",
      live_portal: "लाइव पोर्टल",
      authorized_account: "अधिकृत खाता",
      total_bookings: "कुल बुकिंग",
      approved_visits: "स्वीकृत दौरे",
      pending_reviews: "लंबित समीक्षाएं",
      active_doctors: "सक्रिय डॉक्टर",
      pending_approvals: "लंबित स्वीकृतियां",
      manage_doctors: "डॉक्टर प्रबंधित करें",
      review_appointments: "अपॉइंटमेंट समीक्षा",
      hospital_profile: "अस्पताल प्रोफ़ाइल",
      account_settings: "खाता सेटिंग्स",
      no_appointments: "कोई अपॉइंटमेंट निर्धारित नहीं है",
    },
    es: {
      good_morning: "Buenos Días",
      good_afternoon: "Buenas Tardes",
      good_evening: "Buenas Noches",
      hospitals: "Hospitales",
      dashboard: "Tablero",
      diseases: "Enfermedades",
      medicines: "Medicamentos",
      settings: "Configuración",
      logout: "Cerrar sesión",
      find_hospitals: "Buscar Hospitales",
      ai_chat: "Asistente de Chat IA",
      disease_registry: "Registro de Enfermedades",
      medicine_directory: "Directorio de Medicinas",
      portal_actions: "Acciones Rápidas del Portal",
      my_appointments: "Mis Citas",
      incoming_bookings: "Reservas Entrantes",
      live_portal: "Portal en Vivo",
      authorized_account: "Cuenta Autorizada",
      total_bookings: "Reservas Totales",
      approved_visits: "Visitas Aprobadas",
      pending_reviews: "Revisiones Pendientes",
      active_doctors: "Doctores Activos",
      pending_approvals: "Aprobaciones Pendientes",
      manage_doctors: "Gestionar Doctores",
      review_appointments: "Revisar Citas",
      hospital_profile: "Perfil del Hospital",
      account_settings: "Configuración de la Cuenta",
      no_appointments: "No hay citas programadas",
    }
  };
  
  return translations[lang]?.[key] || translations["en"]?.[key] || key;
};
